name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Clone GitHub repository
        uses: actions/checkout@v2
      
      - name: Check if AutoHotKey is installed
        run: |
          if (Test-Path "$env:ProgramFiles\AutoHotkey\AutoHotkey.exe") {
            Write-Host "AutoHotKey is already installed."
          } else {
            Write-Host "AutoHotKey is not installed. Downloading and installing..."
            $autohotkeyInstaller = "https://autohotkey.com/download/ahk.zip"
            powershell.exe curl $autohotkeyInstaller -o ahk.zip
            powershell.exe Expand-Archive -Path ahk.zip -DestinationPath "$env:ProgramFiles\AutoHotkey\" -Verbose
          }
      
      - name: Check if Inno Setup is installed
        run: |
          if (Test-Path "$env:ProgramFiles (x86)\Inno Setup 6\ISCC.exe") {
            Write-Host "Inno Setup is already installed."
          } else {
            Write-Host "Inno Setup is not installed. Downloading and installing..."
            $innosetupInstaller = "http://files.jrsoftware.org/is/6/innosetup-6.0.4.exe"
            powershell.exe curl $innosetupInstaller -o innosetup-6.0.4.exe
            Start-Process -FilePath "innosetup-6.0.4.exe" -ArgumentList "/VERYSILENT /SUPPRESSMSGBOXES" -Wait
          }

      - name: Run AutoHotKey compiler to generate binary
        run: |
          powershell.exe .\AutoHotKey\Compiler\Ahk2Exe.exe /in LiveEnhancementSuite.ahk /out "Live Enhancement Suite.exe" /icon resources\blueico.ico
